### ISSUE TITLE
Missing dependencies/broken install

### ISSUE THREAD

**Issue by doinkythederp** [purduesigbots/homebrew-pros#14]
When running the PROS CLI after installing it via this package, it exits with an error:

```
Traceback (most recent call last):
  File "/opt/homebrew/bin/pros", line 5, in <module>
    from pros.cli.main import main
  File "/opt/homebrew/Cellar/pros-cli/3.5.1/libexec/lib/python3.10/site-packages/pros/cli/main.py", line 15, in <module>
    from pros.cli.click_classes import *
  File "/opt/homebrew/Cellar/pros-cli/3.5.1/libexec/lib/python3.10/site-packages/pros/cli/click_classes.py", line 4, in <module>
    from rich_click import RichCommand
ModuleNotFoundError: No module named 'rich_click'
```

After running `pip3.10 install rich_click` it still exits with an error:

```
Traceback (most recent call last):
  File "/opt/homebrew/bin/pros", line 5, in <module>
    from pros.cli.main import main
  File "/opt/homebrew/Cellar/pros-cli/3.5.1/libexec/lib/python3.10/site-packages/pros/cli/main.py", line 15, in <module>
    from pros.cli.click_classes import *
  File "/opt/homebrew/Cellar/pros-cli/3.5.1/libexec/lib/python3.10/site-packages/pros/cli/click_classes.py", line 4, in <module>
    from rich_click import RichCommand
  File "/opt/homebrew/lib/python3.10/site-packages/rich_click/__init__.py", line 54, in <module>
    from click.types import DateTime as DateTime
ImportError: cannot import name 'DateTime' from 'click.types' (/opt/homebrew/Cellar/pros-cli/3.5.1/libexec/lib/python3.10/site-packages/click/types.py)
```

**Comment by ayushuk** [comment]
Added missing dependencies.
