### ISSUE TITLE
Error: The 'pyinstaller' distribution was not found and is required by pros-cli

### ISSUE THREAD

**Issue by BNH440** [purduesigbots/homebrew-pros#9]
After upgrading from cli version 3.3.2 to 3.4.1 using homebrew I am receiving this error when running the `prosv5` command.

```
The 'pyinstaller' distribution was not found and is required by pros-cli
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/pros-cli/3.4.1/libexec/lib/python3.10/site-packages/pros/cli/main.py", line 63, in main
    .format(version = get_version()), ctx_obj)
  File "/opt/homebrew/Cellar/pros-cli/3.4.1/libexec/lib/python3.10/site-packages/pros/common/utils.py", line 30, in get_version
    import pkg_resources
  File "/opt/homebrew/Cellar/pros-cli/3.4.1/libexec/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3260, in <module>
    def _initialize_master_working_set():
  File "/opt/homebrew/Cellar/pros-cli/3.4.1/libexec/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3234, in _call_aside
    f(*args, **kwargs)
  File "/opt/homebrew/Cellar/pros-cli/3.4.1/libexec/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3272, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/opt/homebrew/Cellar/pros-cli/3.4.1/libexec/lib/python3.10/site-packages/pkg_resources/__init__.py", line 581, in _build_master
    ws.require(__requires__)
  File "/opt/homebrew/Cellar/pros-cli/3.4.1/libexec/lib/python3.10/site-packages/pkg_resources/__init__.py", line 909, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/opt/homebrew/Cellar/pros-cli/3.4.1/libexec/lib/python3.10/site-packages/pkg_resources/__init__.py", line 795, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pyinstaller' distribution was not found and is required by pros-cli
```

System Details:
MacOS Ventura 13.0.1
Apple Silicon

**Comment by BNH440** [comment]
Realized this better fits in the pros-cli repo so I'll close this
